laravel/sanctum

src/AirlockServiceProvider.php
This pull request removes the usage of `config('airlock.tokens', true)` that apparently does not exists.
=> Removes unused usage of `config('airlock.tokens', true)`

src/Airlock.php
Without this change I always need to manually set the model that should be used with `Airlock::useUserModel(...)` instead of Airlock using the model that I have configured in the `config/auth.php` file.
After this change the `userModel` will either return the model from the configuration or the default that is defined on the class.
=> use configured model first for userModel

src/AirlockServiceProvider.php, src/PersonalAccessToken.php
this **PR** removes unwanted expires_at from $casts since the column has been removed . and also make sure to pass expiration minutes as second param to **Guard** cause all the tokens will be valid even if they expired
=> Remove unwanted expires_at from $casts & Pass expiration minutes to Gurad

src/PersonalAccessToken.php
`HasApiTokens@withAccessToken` expects a class implementing `\Laravel\Airlock\Contracts\HasAbilities`
=> PersonalAccessToken implements HasAbilities

src/Guard.php, tests/GuardTest.php
We were always using the `web` user model class for both session and token authentication (at `supportsTokens()`. For token authentication, we have to use Airlock's user model.
Fixes #26
=> Fix custom user model

README.md
In the example for Authenticating Mobile Applications, the `$request` object references `device_name` when creating the token; however, the `validate` method does not ensure this value is present.
To address this, I required `device_name` to be present in the `$request` object, which I suspect would be a suitable solution.
Hope this helps!
=> Add device_name to request

README.md, database/migrations/2019_12_14_000001_create_personal_access_tokens_table.php, src/Airlock.php, src/Guard.php, src/HasApiTokens.php, src/PersonalAccessToken.php, tests/GuardTest.php
this **PR** resolves #10 . 
by making **PersonalAccessToken** model polymorphic will allow multiple models to be authenticated through airlock tokens .
for example if i have **Pharmacist** & **Doctor** models .  and would authenticate both of them through api  . i would have to [implement this solution](https://github.com/laravel/airlock/issues/10#issuecomment-573019653) which is in my opinion a little bit  tedious .
but by making **PersonalAccessToken** model polymorphic. this will allow implementing the above use case without any extra boilerplate . 
and also customization to user Model through **userModel()** won't be needed any more . cause polymorphic relation will support any other models .
=> Modify PersonalAccessToken Model to be polymorphic

README.md, src/Airlock.php, tests/Feature/ActingAsTest.php
This pull request should resolve issue #50 by adding the requested functionality.
- `Airlock::actingAs` with tests for `auth:api` and abilities
=> Added user mocking through Airlock using actingAs

config/airlock.php
Whilst `localhost` is a good default setting, for APIs that are installed in multiple environments (dev, test, prod) it is sensible to allow each environment to configure its stateful Airlock domains via the .env file (or alternative approaches e.g. AWS Elastic Beanstalk Configuration).
=> Allow .env configuration of airlock stateful domains (Take 2)

config/airlock.php
Currently the airlock middleware blocks requests from 127.0.0.1 by default only allowing the use localhost itself. This may lead to confusion to certain users especially since if you use artisan serve it recommends the use of 127.0.0.1:8000.
=> [1.x] Allow localhost ip access by default

composer.json
Updates composer dependency 6.0.0 to 6.9.0 to resolve the package throwing an error if used with earlier versions than 6.9.0 as detailed in Feature Request #88
=> [1.x] Updates composer dependency 6.0 => 6.9

config/sanctum.php, src/Guard.php
I am building a Laravel package which uses sanctum. It was really a missing peace in the eco system. Thanks for this!
However, since I have an additional guard in my package, I had problems to make the described stateful requests.
There was also no way to swap out the implementation via the container because it is instantiated with `new` instead of using the container.
This little change would give me the possibility to go on with this package. I think there is also a discussion about this topic in #20  
There are no breaking changes.
=> [2.x] Make the guard configurable

src/Sanctum.php, tests/ActingAsTest.php
```php
Sanctum::actingAs(
factory(User::class)->create(),
['*']
);
```
Doesn't work as described in the docs.
The mockery instance ends up looking for the argument `'*'` instead of responding with `true` to any `can()` call like the [PersonalAccessToken](https://github.com/laravel/sanctum/blob/2.x/src/PersonalAccessToken.php#L58) does.
A change to `Sanctum::actingAs()` fixes this.
=> actingAs any ability

src/Guard.php
Quick small fix. I don't know if it's 7.4 related, but when I call 
```php
class_uses_recursive(null);
```
it gives me `ErrorException : class_parents(): object or string expected`
I just about the function to test if `$tokenable` if available even before checking the `HasApiTokens` trait usage.
=> Enhance supportsTokens check

src/Guard.php, src/PersonalAccessToken.php
In reference to this issue https://github.com/laravel/sanctum/issues/9
You can already customize how a token is generated by overriding the `createToken` method in your tokenable model.
This PR adds the ability to customize how you'd retrieve a token from the DB, this can be done by defining your own `PersonalAccessToken` class and override the new method `findToken`
=> [2.x] Allow customizing the query used to get the token

src/SanctumServiceProvider.php
Config provider is not used when creating a [RequestGuard](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Auth/AuthManager.php#L229) unlike [SessionGuard](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Auth/AuthManager.php#L123).
=> No need to specify a provider

src/HasApiTokens.php, src/PersonalAccessToken.php, tests/HasApiTokensTest.php
This PR prefixes the plain text token with the token ID so we can lookup that token with a better query performance.
=> [2.x] more performant tokens lookup

src/Http/Middleware/EnsureFrontendRequestsAreStateful.php, tests/EnsureFrontendRequestsAreStatefulTest.php
I've figured out an issue with EnsureFrontendRequestsAreStateful middleware. If no value specified for stateful domains in .env, it is considered as blank string and middleware assumes requests is from FrontEnd and applying all following middleware, which results into 419 exception.
- Set in .env `SANCTUM_STATEFUL_DOMAINS=` without any value
- Make POST request without referrer to guest route registered in api.php (consider calling API from mobile App)
- `EnsureFrontendRequestsAreStateful` middleware assumes request is from FrontEnd as `Str::is()` is matching blank string with null and returns true.
=> [2.x] 419 Exception with requests without referrer

config/sanctum.php, src/Http/Middleware/EnsureFrontendRequestsAreStateful.php
Added the option to select the middleware for cookies encryption to allow the exclusion of some cookies.
The current implementation use the EncryptCookies middleware of laravel, ignoring the potential changes made by the user in App\Http\Middleware\EncryptCookies.php . This pull request aims to correct the behaviour.
=> EncryptCookies middleware option in config/sanctum.php

src/PersonalAccessToken.php
PersonalAccessToken::findToken can also return `null`. This PR adds it to the return doc block.
=> PersonalAccessToken::findToken can also return `null`

src/Http/Middleware/EnsureFrontendRequestsAreStateful.php, tests/EnsureFrontendRequestsAreStatefulTest.php
Adds an `origin` fallback if the `referer` has been stripped. Closes #203.
=> [2.x] Adds origin header fallback

src/SanctumServiceProvider.php, tests/GuardTest.php
This PR provides the specified user provider to the `sanctum` guard.
Without that, the `Illuminate\Auth\RequestGuard` is constructed without a user provider by default, which is inconsistent with the `Laravel\Sanctum\Guard` callable which accepts the specified user provider.
I've added tests to prove that the `sanctum` guard is not properly configured:
The `Laravel\Sanctum\Guard` callable accepts the specified provider in the constructor from the configuration, and validates if the provider model matches the authenticated model. This part is working correctly.
In the service provider, the actual guard `Illuminate\Auth\RequestGuard` is constructed with the default application provider which is `null`, instead of the specified provider in the configuration.
So, calling …
=> [2.x] Fix user provider in `sanctum` guard

config/sanctum.php, src/Guard.php
This pull request adds support to multiple guards for SPA Authentication.
It will take guards set in `sanctum.guards` iterate and return the first item that matches.
These guards should correspond with the guards that are already present in the `auth` configuration file.
=> [2.x] Add multiple guard support for SPA auth

database/migrations/2019_12_14_000001_create_personal_access_tokens_table.php, src/Guard.php, src/HasApiTokens.php, src/PersonalAccessToken.php, tests/GuardTest.php, tests/HasApiTokensTest.php
Adds an expires_at timestamp to tokens. If the expires_at has passed, the token can no longer be used. 
This may allow users to set different expiration times for different tokens. So you can create a token used for a one-time import that expires in automatically in a week, and a token that generates daily reports that doesn't expire.
This also lets developers enforce different expiration times for different tokens based on the type of user, or the privileges of the token.
=> [3.x] Add expires_at functionality to tokens.

src/Http/Middleware/EnsureFrontendRequestsAreStateful.php
Fixes an issue in PHP 8.1 where a request with no `Referer` or `Origin` header will throw a deprecation warning (transformed to an `ErrorException` in tests) when `Str::replaceFirst` attempts to call `strpos` with `null` as the first argument.
Once PHP 8.1 is added to the matrix, this will be automatically covered by [`test_requests_are_not_stateful_without_referer`][1].
**Context:**
* I recently switched my project from Passport to Sanctum, using cookie-based SPA auth
* When I later added PHP 8.1 to the GH Actions workflow, all frontend tests hitting Sanctum's middleware were failing
---
```
[2021-03-06 13:01:23] testing.ERROR:
strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated { "userId":1,
"exception":"[object] (
ErrorException(code: 0):
strpos(): Passing …
```
=> [PHP 8.1] Avoid running string functions when domain is null

src/HasApiTokens.php
As described in #261 a changed primary key name will not be used when creating tokens
=> [2.x] Changed Primary Key will not be used in created token's plainTextToken

config/sanctum.php, phpunit.xml.dist, tests/DefaultConfigContainsAppUrlTest.php
Added the application's URL from `.env`'s `APP_URL` to the default value of `sanctum.stateful` configuration.
In my experience (teaching new Laravel developers) not having the application's URL among default stateful domains leads to a lot of headache when deploying to a production environment. The URL changes from e.g. `localhost:3000` to `www.test.com` and suddenly a new configuration value must be added into `.env` which was not needed until now.
While everyone expects they should change the `APP_URL` when moving to a new environment, few also remember to add `SANCTUM_STATEFUL_DOMAINS`
This is also hard to notice because the application works, only the requests which should be authenticated are not.
Added the host part of the `APP_URL` environment value to `/config/sanctum.php` 
I …
=> [2.x] Environment APP_URL added into the default sanctum.stateful configuration

src/Contracts/HasApiTokens.php, tests/ActingAsTest.php, tests/GuardTest.php, tests/HasApiTokensTest.php
In a recent project using Sanctum I wanted to check if the `User`/`Model`/`Authenticatable`/whatever uses the `HasApiTokens` trait. Currently this can only be achieved by one of the following options:
```php
// A. check trait usage
if (! in_array(HasApiTokens::class, class_uses($user)) {
throw new Exception();
}
// B. check method existence
if (! method_exists($user, 'currentAccessToken')) {
throw new Exception();
}
```
* Option A will work, but static analysis will not understand that `$user` has a specific set of methods.
* Option B does support static analysis, but is messy, because it doesn't really check for the trait (or specific contract).
Therefore I've added a contract to complement the trait.
```php
use Laravel\Sanctum\Contracts\HasApiTokens as HasApiTokensContract;
if (! $user …
```
=> [2.x] Add HasApiTokens contract to complement trait

CHANGELOG.md, src/Guard.php, src/Sanctum.php, tests/GuardTest.php
Currently Sanctum has a bit of a shotgun approach to validation. You either specify: 
1. how long *all tokens* are valid
2. they are *all* valid forever
There is no easy user control for overwriting this behavior.
By implementing this feature developers are able to make:
- Single use tokens
- Limited time tokens & unlimited time tokens at the same time
- Use any other business logic that prevents a specific user from being able to use that token
The `Guard` now checks for a validation callback on the `Sanctum` class. This callback receives:
- The used access token
- The current validation state (`bool`) according to the `Guard`
To make a **single use token** you can to this for instance:
```php
// AppServiceProvider.php
use Laravel\Sanctum\PersonalAccessToken
use Laravel\Sanctum\Sanctum; …
```
=> More granular control over token validation

CHANGELOG.md, src/Guard.php, tests/GuardTest.php
As a follow up to #275 and because of the comment @driesvints made on that PR:
> @doekenorg best that you send a follow up pr as its unlikely that Taylor will see your reply
I noticed you removed the `$isValid` parameter from the callback in your reformatting. Any particular reason you did this? I would like to ask to revert that because now I cannot actually **add** to the validation, but only **completely replace it**. If I don't know if the `Guard` deemed it valid I need to check those validations again myself inside the callback; which is a bit of a pain.
Say I want to use the normal behavior, but only use the token one time, I now have to re-add the checks to see if the token hasn't expired already. This seems a bit counter productive to me. It can even make the validation less …
=> Revert removal is valid

src/Guard.php, src/PersonalAccessToken.php
**Problem**
Sanctum updates the access token's `last_used_at` property every time an API is authenticated using sanctum guard. This db query happens in the initial phase of the request cycle. This causes all the subsequent db queries to go to writer host even in the case of read operations.
**Solution**
Saving the updated `last_used_at` operation is moved to the application terminating event.
=> Ignore updating `last_used_at` for deciding the DB connection host

src/SanctumServiceProvider.php
In `SanctumServiceProvider` some places it was taking instance by `$this->app` which was giving the wrong app instance in the Octane environment.
it was `spl_object_hash` of different app instances
=> Resolving wrong app instance on Octane

composer.json, src/Console/Commands/PruneExpired.php, src/SanctumServiceProvider.php, tests/PruneExpiredTest.php
This command has long been needed by developers.
A similar command is present in Telescope and Passport packages.
=> [2.x] Add sanctum:prune-expired command for removing expired tokens.

src/Guard.php, src/Sanctum.php, tests/GuardTest.php
I have a use-case with an application where I need to send an authentication token via a different header instead of using the Authorization header due to the app (being a proxy type application) needing to pass the Authorization header in a different capacity.
This pull request adds the capability to Sanctum to specify a different method of getting the token from the request by setting a callback to the Sanctum object, falling back to using the bearer token if nothing has been set.
=> Added custom auth token header support

.github/workflows/tests.yml, composer.json
In preparation for v3, we'll drop old Laravel and PHP versions and make Laravel v9 and PHP 8.0 the new minimums.
=> [3.x] Drop old Laravel and PHP versions

composer.json, src/Console/Commands/PruneExpired.php, tests/PruneExpiredTest.php
This pull request improves the console output of Sanctum.
=> [3.x] Improves console output

database/migrations/2019_12_14_000001_create_personal_access_tokens_table.php
This is the migration file in laravel：
`2019_12_14_000001_create_personal_access_tokens_table.php`
```
....
Schema::create('personal_access_tokens', function (Blueprint $table) {
$table->id();
...
```
This is the migration file in sanctum：
`2019_12_14_000001_create_personal_access_tokens_table.php`
```
...
Schema::create('personal_access_tokens', function (Blueprint $table) {
$table->bigIncrements('id');
...
```
I think the id field should be kept consistent.
=> Update migration's primary identifier change

src/Console/Commands/PruneExpired.php, tests/PruneExpiredTest.php
Closes #384
This still requires the `sanctum.expiration` to be set.
=> Prune expires_at tokens

src/Guard.php, tests/GuardTest.php
This fixes validation for bearer tokens that contain model id (**1**|xxxxxxxx..).
If you alter this id, then server will return 500 error, because there is no format validation (yes, there is some validation regarding token expiration, and presence of the token at all, but that's not enough).
Just alter the id param for bearer token. Make it something not a valid integer.
This results 500 Server error response for any Sanctum-protected api endpoint.
(mssql server specific, but I think this can be DB-agnostic):
```
SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Error converting data type nvarchar to bigint. (SQL: select top 1 * from [personal_access_tokens] where [personal_access_tokens].[id] = 1ABC
```
401 Unauthorized HTTP status
=> [3.x] Fix bearer token format validation

src/Http/Controllers/CsrfCookieController.php
Php Doc block return type fixes in CsrfCookieController
=> Php Doc block: return type fixes in CsrfCookieController

src/HasApiTokens.php, tests/Feature/HasApiTokensTest.php
php is interesting: this change makes it easier to validate the checksum in different langauges by using the IEEE CRC32 polynomial
So when implementing the validator for the checksum I noticed that PHP actually has a rich history with CRC32.
The `crc32()` method uses the IEEE polynomial that's become the defacto standard, but the `hash('crc32'…)` method uses a different polynomial that then becomes more difficult to validate in languages other than php. The `hash()` method calls the algorithm `crc32b` when you want to use the IEEE polynomial.
After working away on this issue in golang for awhile, I realized it would be better for the community to update it to the more universal polynomial.
After this change the one last thing to watchout for with this is that php reverses the crc32 …
=> Use crc32b instead of crc32

src/Sanctum.php
Have a kind of an odd case where we're communicating between two applications and want to only allow for authorizing via Sanctum (on one endpoint) with a custom method of getting the access token. (The original app uses Passport, the new app uses Sanctum, so the HasApiTokens traits conflict on the User model).
```php
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Laravel\Sanctum\Sanctum;
class SwapTokenController extends Controller
{
public function __invoke(SwapTokenRequest $request)
{
$originalCallback = Sanctum::$accessTokenRetrievalCallback ?? null;
try {
Sanctum::getAccessTokenFromRequestUsing(function (Request $request) {
if (! $sanctumTokenString = $request->get('sanctum_token')) {
return null;
}
return $sanctumTokenString;
});
/** @var User|null $user */ …
```
=> Accept null as a parameter for `Sanctum@getAccessTokenFromRequestUsing()`

.github/workflows/tests.yml, .gitignore, composer.json, phpstan.neon.dist, phpunit.xml.dist
https://github.com/laravel/sanctum/commit/0d4019d3ce52087f1f6e7952e97097ed59629e43 Changes made it incompatible with Laravel 10 and lower. 
It might be best to have Sanctum for Laravel 11 to drop support for older Laravel versions.
=> Laravel 11 Supports

src/Http/Controllers/CsrfCookieController.php
Used PHP 8 named arguments instead of passing default values for the first argument, to enhance readability.
=> Updated `CsrfCookieController` to use named arguments

src/HasApiTokens.php
I need to rewrite the `createToken` method, but the way the token is generated does not need to be modified by me. By extracting the method, I can avoid the impact of my rewrite on the original function.
=> Extract generate token method

src/Contracts/HasApiTokens.php
The contract does not include the third parameter `DateTimeInterface $expiresAt`.
Contract:
```php
public function createToken(string $name, array $abilities = ['*']);
```
Trait:
```php
public function createToken(string $name, array $abilities = ['*'], DateTimeInterface $expiresAt = null)
```
From PHPStan:
```
Error: Method Laravel\Sanctum\Contracts\HasApiTokens::createToken() invoked with 3 parameters, 1-2 required.
```
***Should this pull request be made against 3.x instead?***
=> Matching method to contract for createToken()
